name: Release

env:
  PUBLIC_NUGET_SERVER: https://api.nuget.org/v3/index.json
  SIMCUBE_NUGET_API_KEY: ${{ secrets.PUBLIC_NUGET_TOKEN }}
  DOTNET_NOLOGO: true
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  DOTNET_CLI_TELEMETRY_OPTOUT: true

on:
  push:
    tags:
      - "*"

jobs:
  build-test-pull-request:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '6.0.x'
          include-prerelease: false

      - name: Build, Test and Pack
        run: |
          dotnet tool restore
          dotnet cake --pack true

      - name: Push to nuget
        working-directory: artifacts/
        run: dotnet nuget push *.nupkg -s $PUBLIC_NUGET_SERVER -k $SIMCUBE_NUGET_API_KEY